version: '3'

networks:
    app-network: null

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_${APP_NAME}
        ports: 
            - 80:80
        volumes: 
            - ./src:/var/www/html
            - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks:
            - app-network
    mysql:
        image: mysql:5.7.33
        container_name: mysql_${APP_NAME}
        restart: unless-stopped
        tty: true
        ports: 
            - 3306:3306
        environment: 
            MYSQL_DATABASE: pm
            MYSQL_USER: havt
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 123456aa
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - app-network
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php_${APP_NAME}
        user: ${UID:-1000}:${GID:-1000}
        volumes: 
            - ./src:/var/www/html
        ports: 
            - 9000:9000
        networks: 
            - app-network

    composer:
        image: composer:latest
        container_name: composer_${APP_NAME}
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks: 
            - app-network